// <auto-generated />
namespace B2B.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class revertidentity04change : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(revertidentity04change));
        
        string IMigrationMetadata.Id
        {
            get { return "202006101258433_revert-identity-0.4-change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
