// <auto-generated />
namespace B2B.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateproductaddcompanyid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateproductaddcompanyid));
        
        string IMigrationMetadata.Id
        {
            get { return "202007031126172_update-product-add-company-id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
